# Generated by Django 2.1.2 on 2019-04-07 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ATK',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rincian', models.CharField(max_length=200)),
                ('tanggal_input', models.DateTimeField(auto_now_add=True)),
                ('jumlah', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Handling',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rincian', models.CharField(max_length=200)),
                ('tanggal_input', models.DateTimeField(auto_now_add=True)),
                ('jumlah', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Kendaraan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rincian', models.CharField(max_length=200)),
                ('tanggal_input', models.DateTimeField(auto_now_add=True)),
                ('jumlah', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='La',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rincian', models.CharField(max_length=200)),
                ('tanggal_input', models.DateTimeField(auto_now_add=True)),
                ('jumlah', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Paspor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rincian', models.CharField(max_length=200)),
                ('tanggal_input', models.DateTimeField(auto_now_add=True)),
                ('jumlah', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Pembukuan_Haji',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rincian', models.CharField(max_length=200)),
                ('tanggal_input', models.DateTimeField(auto_now_add=True)),
                ('jumlah', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Pembukuan_Honor_Karyawan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rincian', models.CharField(max_length=200)),
                ('tanggal_input', models.DateTimeField(auto_now_add=True)),
                ('jumlah', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Pembukuan_Pajak',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rincian', models.CharField(max_length=200)),
                ('tanggal_input', models.DateTimeField(auto_now_add=True)),
                ('jumlah', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Pembukuan_Umroh',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rincian', models.CharField(max_length=200)),
                ('tanggal_input', models.DateTimeField(auto_now_add=True)),
                ('jumlah', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Tiket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rincian', models.CharField(max_length=200)),
                ('tanggal_input', models.DateTimeField(auto_now_add=True)),
                ('jumlah', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Transfortasi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rincian', models.CharField(max_length=200)),
                ('tanggal_input', models.DateTimeField(auto_now_add=True)),
                ('jumlah', models.IntegerField()),
            ],
        ),
    ]
