# Generated by Django 2.1.2 on 2019-04-17 11:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pembukuan', '0002_auto_20190415_1525'),
    ]

    operations = [
        migrations.AddField(
            model_name='tiket',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
