# Generated by Django 2.1.2 on 2019-04-17 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pembukuan', '0003_tiket_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tiket',
            name='tanggal_input',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
