# Generated by Django 2.1.2 on 2019-04-17 11:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pembukuan', '0004_auto_20190417_1831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tiket',
            name='tanggal_input',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
