# Generated by Django 2.1.2 on 2019-04-17 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pembukuan', '0005_auto_20190417_1832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tiket',
            name='tanggal_input',
            field=models.DateField(),
        ),
    ]
