# Generated by Django 2.1.2 on 2019-04-09 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data_jemaah', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pembayaran_Jemaah_Haji',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jumlah', models.IntegerField(default=0)),
                ('waktu', models.DateField(auto_now_add=True)),
                ('jemaah', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='data_jemaah.Jemaah_Hajis')),
            ],
        ),
    ]
