# Generated by Django 2.1.2 on 2019-04-10 03:20

import data_jemaah.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('data_jemaah', '0002_pembayaran_jemaah_haji'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jemaah_Umroh',
            fields=[
                ('id', models.CharField(default=data_jemaah.models.create_id, max_length=100, primary_key=True, serialize=False)),
                ('nama_lengkap', models.CharField(max_length=200)),
                ('foto', models.ImageField(upload_to='')),
                ('alamat', models.TextField()),
                ('tempat_lahir', models.CharField(max_length=100)),
                ('tanggal_lahir', models.CharField(max_length=100)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('tunggakan', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pembayaran_Jemaah_Umroh',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jumlah', models.IntegerField(blank=True, null=True)),
                ('waktu', models.DateField(auto_now_add=True)),
                ('jemaah', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='data_jemaah.Jemaah_Umroh')),
            ],
        ),
        migrations.CreateModel(
            name='Umroh',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pemberangkatan', models.CharField(max_length=100)),
                ('harga', models.IntegerField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='haji',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pembayaran_jemaah_haji',
            name='jumlah',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jemaah_umroh',
            name='rombongan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rombongan', to='data_jemaah.Umroh'),
        ),
    ]
