# Generated by Django 2.1.2 on 2019-04-10 13:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data_jemaah', '0003_auto_20190410_1020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jemaah_hajis',
            name='rombongan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='data_jemaah.Haji'),
        ),
    ]
