# Generated by Django 2.1.2 on 2019-04-11 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_jemaah', '0005_auto_20190410_2031'),
    ]

    operations = [
        migrations.AddField(
            model_name='jemaah_hajis',
            name='no_hp',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jemaah_umroh',
            name='no_hp',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
