# Generated by Django 2.1.2 on 2019-04-11 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_jemaah', '0006_auto_20190411_1730'),
    ]

    operations = [
        migrations.AddField(
            model_name='jemaah_hajis',
            name='no_ktp',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jemaah_umroh',
            name='no_ktp',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
